# Generated by Django 4.0.3 on 2022-04-25 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_mail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_mail', models.CharField(max_length=200, verbose_name='Почта пользователя')),
            ],
        ),
        migrations.AlterModelOptions(
            name='useragreement',
            options={'verbose_name': 'Соглашение', 'verbose_name_plural': 'Соглашения'},
        ),
        migrations.RenameField(
            model_name='useragreement',
            old_name='Useragreement_text',
            new_name='useragreement_text',
        ),
    ]
