# Generated by Django 4.0.3 on 2022-04-27 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_user_mail_alter_useragreement_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user_mail',
            options={'verbose_name': 'Почта пользователя', 'verbose_name_plural': 'Почты пользователей'},
        ),
        migrations.AlterField(
            model_name='user_mail',
            name='user_mail',
            field=models.CharField(max_length=100, verbose_name='Почта пользователя'),
        ),
    ]
