# Generated by Django 4.0.3 on 2022-04-29 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_remove_user_mail_user_telegram_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_telegram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_telegram', models.CharField(max_length=100, verbose_name='Телеграм пользователя')),
                ('user_telegram_sender', models.CharField(default='sapdloginkey@gmail.com', max_length=100, verbose_name='Телеграм группа с кодами')),
            ],
            options={
                'verbose_name': 'Телеграм пользователя',
                'verbose_name_plural': 'Телеграмы пользователей',
            },
        ),
    ]
