# Generated by Django 4.0.3 on 2022-04-29 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0006_user_telegram'),
    ]

    operations = [
        migrations.CreateModel(
            name='Telegram_group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_telegram_sender', models.CharField(max_length=100, verbose_name='Телеграм группа с кодами')),
            ],
            options={
                'verbose_name': 'Соглашение',
                'verbose_name_plural': 'Соглашения',
            },
        ),
        migrations.RemoveField(
            model_name='user_telegram',
            name='user_telegram_sender',
        ),
    ]
